### ISSUE TITLE
Select page / Select all buttons?

### ISSUE THREAD

**Issue by laytya** [shirsig/postal#11]
Can you add [Select page] / [Select all] buttons? And do not open all mails w/ out confiramation....

![img](https://media-curse.cursecdn.com/attachments/213/36/8cb284e4444ff21aa64a000ed0132d7d.jpg)

**Comment by shirsig** [comment]
Honestly, this seems like overkill. Especially with the right-click to directly loot feature that was recently added. I'm even thinking of removing the checkboxes.

There will never be a confirmation for "open all", sorry. If you accidentally click the button (not likely imo) just walk away from the mailbox. What I might add is an "abort" button though.

**Comment by Road-block** [comment]
I know this isn't a democracy but I'd like to keep the checkboxes feature.  
I mean I understand that you can "right click as you go" instead of checking boxes and there's minimal difference but I still prefer the 2-step process on some occasions.  
Use case: I click a bunch of stuff that's already partial stacks in my bags, for some reason my mind processes that easier when I can go through the list of things and check them off > look them over > click to loot.  
But it's no big deal anyway I can live with either.

**Comment by shirsig** [comment]
Well, I guess I'm biased because I've literally never used the checkboxes anyway and always just open all, so since I barely see the purpose for selective opening at all I think having even two features to do basically that same thing is kinda unnecessary. Also in general I'd rather keep the interface as unmodified/blizzlike as possible.
