### ISSUE TITLE
Initial loading of addon displays mail as unread

### ISSUE THREAD

**Issue by xC0DEB10C** [shirsig/Postal#2]
Basically when ever the UI reloads, it shows as if you have mail on the minimap.

**Comment by shirsig** [comment]
Yes, this cannot be prevented. There's a bug in the wow client that when the last mail is opened through automation it will not recognize the mailbox as empty. Old vanilla mail addons like GMail/CT_MailMod don't even hide the icon at all. In postal I'm manually checking if the mailbox is empty and hiding the icon if it is, but this can only be done when at the mailbox. There's no way of knowing if, after reloading the ui, the icon is there because of the bug or because new mail has arrived in the meantime.
